[package]
name = "triangle_segments_demo"
version = "0.1.0"
edition = "2021"

[dependencies]
macroquad = "0.4"
glam = "*"

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"
lto = true

